/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

#ifndef ARTFID_H
#define ARTFID_H

/******************************************************************
   File Name: ArtFid.H


   Purpose: This file will contain defines for all the critter
            fids for the game. The pids can be found by using mapper
            and selecting the critter and then edit. The FID will show
            up on the debug screen preceded by "proto->fid = ".
            Note: all the FID defines with that only have () were not
            in the game at the time that this file was made so if they
            show up, make 'em.


   Created: April 28, 1998
******************************************************************/


#define FID_HAPOWR                  ()
#define FID_HAROBE                  (16777247)
#define FID_HFCMBT                  ()
#define FID_HFJMPS                  (16777220)
#define FID_HFLTHR                  (16777221)
#define FID_HFMAXX                  (16777222)
#define FID_HFMETL                  (16777223)
#define FID_HFPRIM                  (16777277)
#define FID_HMCMBT                  ()
#define FID_HMJMPS                  (16777227)
#define FID_HMLTHR                  (16777228)
#define FID_HMMAXX                  (16777229)
#define FID_HMMETL                  (16777230)
#define FID_HMWARR                  (16777278)
#define FID_HMBJMP                  ()
#define FID_HMBMET                  (16777225)
#define FID_MABROM                  (16777231)
#define FID_MACLAW                  (16777267)
#define FID_MACLW2                  (16777276)
#define FID_MADDOG                  (16777232)
#define FID_MAFEYE                  (16777270)
#define FID_MAHAND                  (16777233)
#define FID_MAMANT                  (16777268)
#define FID_MAMRAT                  (16777235)
#define FID_MAMTNT                  (16777237)
#define FID_MAMTN2                  (16777236)
#define FID_MAMURT                  (16777271)
#define FID_MAPLNT                  (16777281)
#define FID_MAROBO                  (16777299)
#define FID_MASCP2                  (16777275)
#define FID_MASCRP                  (16777238)
#define FID_MASPHN                  ()
#define FID_MASRAT                  (16777240)
#define FID_MATHNG                  ()
#define FID_NABLUE                  ()
#define FID_NABRWN                  ()
#define FID_NACHLD                  (16777243)
#define FID_NAGHUL                  (16777244)
#define FID_NAGLOW                  (16777245)
#define FID_NAPOWR                  ()
#define FID_NAROBE                  (16777247)
#define FID_NFBRLP                  (16777249)
#define FID_NFMAXX                  (16777250)
#define FID_NFMETL                  (16777251)
#define FID_NFPEAS                  (16777252)
#define FID_NFPRIM                  (16777279)
#define FID_NFTRMP                  (16777253)
#define FID_NFVRED                  ()
#define FID_NMBPEA                  (16777255)
#define FID_NMBRLP                  (16777256)
#define FID_NMBSNP                  (16777257)
#define FID_NMDOCC                  (16777273)
#define FID_NMGRCH                  ()
#define FID_NMLOSR                  (16777259)
#define FID_NMLTHR                  (16777260)
#define FID_NMMAXX                  (16777261)
#define FID_NMPEAS                  (16777264)
#define FID_NMWARR                  (16777280)
#define FID_MAGKO2                  (16777283)
#define FID_MAGCKO                  (16777284)
#define FID_NMVALT                  (16777285)
#define FID_HANPWR                  (16777287)
#define FID_BOXER                   (16777312)

#endif // ARTFID_H
